apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://manasvitiwari08_db_user:manasvi08@cluster0.mrcwcfb.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "smartpg_super_secret_jwt_key_2025" 